---
name: hs-dbus-signature weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 25 3 * * 0
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - dependencies: >
              pylint
              python3-hypothesis
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
    runs-on: ubuntu-latest
    container: fedora:39  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}
